window.LANG = {
  en: {
    about: "About",
    close: "Close",
    start: "Start",
    stop: "Stop",
    step: "Step",
    reset: "Reset",
    export: "Export",
    update: "Update",
    initialising: "Initialising",
    loaded: "Loaded...",
    running: "Running",
    stopped: "Stopped",
    tip_update: "TIP: Untick the 'Update' option to improve performance",
    tip_sound: "TIP: Some browsers require human interaction before they play sound. So try clicking, and refreshing the page, if you hear nothing",
    keys: "Keys:",
    insert_coin: "C : Insert coin",
    player1_start: "1 : Player 1 start",
    player2_start: "2 : Player 2 start",
    left1: "Z : Left (player 1)",
    right1: "X : Right (player 1)",
    fire1: ". : Fire (player 1)",
    left2: "A : Left (player 2)",
    right2: "S : Right (player 2)",
    fire2: "L : Fire (player 2)",
    drag_asm: "Drag and drop files here to assemble them...",
    drag_dis: "Drag and drop files here to disassemble them...",
    drag_conv: "Drag and drop files here to convert them...",
    asm_to_bin: "Assembly source ===>  Binary",
    export_xml: "Export to XML",
    asm_source: "Assembly source",
    hex: "Hex",
    errors: "Errors",
    full_map: "Full map",
    equates: "Equates",
    debugger: "Debugger",
    enter_command: "Enter command. e.g. help",
    enter: "Enter",
    javascript: "JavaScript",
    c_cpp: "C/C++",
    intel_hex: "Intel HEX",
    hex_json: "HEX.JSON",
    hex_string: "Hex string",
    memory_source: "Source Memory",
    memory_dest: "Destination Memory",
    about_p1: "This emulator was built using the EMF system, designed and implemented by Steven Goodwin, between 2011 and 2020.",
    about_p2: "First, the machine is defined with a custom description language. Each component part, along with its interactives, it's explained in a human-friendly, and machine-readable, format.",
    about_p3: "Then, this description is processed to generate an emulator, assembler, and dissembler for the machine in question. This can be in any language, but is currently targetted to JavaScript.",
    about_p4: "Finally, these files are glued into the JavaScript EMF framework, which handles the UI-specific components.",
    about_copyright: "EMF is Copyright by Steven Goodwin, 2011-2020. All rights reserved.",
    lang_en: "EN",
    lang_tw: "繁體"
  },
  tw: {
    about: "關於",
    close: "關閉",
    start: "開始",
    stop: "停止",
    step: "單步",
    reset: "重設",
    export: "匯出",
    update: "自動更新",
    initialising: "初始化中",
    loaded: "已載入...",
    running: "執行中",
    stopped: "已停止",
    tip_update: "提示：取消 '自動更新' 可提升效能",
    tip_sound: "提示：有些瀏覽器需互動後才能播放聲音，若沒聲音請點擊或重新整理頁面",
    keys: "按鍵說明：",
    insert_coin: "C：投幣",
    player1_start: "1：玩家1開始",
    player2_start: "2：玩家2開始",
    left1: "Z：左（玩家1）",
    right1: "X：右（玩家1）",
    fire1: ".：發射（玩家1）",
    left2: "A：左（玩家2）",
    right2: "S：右（玩家2）",
    fire2: "L：發射（玩家2）",
    drag_asm: "拖曳檔案到此可組譯...",
    drag_dis: "拖曳檔案到此可反組譯...",
    drag_conv: "拖曳檔案到此可轉換...",
    asm_to_bin: "組譯原始碼 ===> 二進位",
    export_xml: "匯出為 XML",
    asm_source: "組譯原始碼",
    hex: "十六進位",
    errors: "錯誤",
    full_map: "完整對應表",
    equates: "符號定義",
    debugger: "除錯器",
    enter_command: "輸入指令，例如 help",
    enter: "送出",
    javascript: "JavaScript",
    c_cpp: "C/C++",
    intel_hex: "Intel HEX",
    hex_json: "HEX.JSON",
    hex_string: "Hex 字串",
    memory_source: "來源記憶體",
    memory_dest: "目的記憶體",
    about_p1: "此模擬器使用 EMF 系統建構，由 Steven Goodwin 在 2011 至 2020 年間設計與實作。",
    about_p2: "首先，機器以自訂描述語言定義。每個組件部分及其互動性，都以人性化且機器可讀的格式說明。",
    about_p3: "接著，此描述會被處理以產生該機器的模擬器、組譯器與反組譯器。這可以是任何語言，但目前以 JavaScript 為目標。",
    about_p4: "最後，這些檔案會整合到 JavaScript EMF 框架中，處理 UI 特定組件。",
    about_copyright: "EMF 版權所有 Steven Goodwin，2011-2020。保留所有權利。",
    lang_en: "EN",
    lang_tw: "繁體"
  }
};
